/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AssociativeInput: typeof import('./../components/AssociativeInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./../components/Header.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpCaretRight: typeof import('~icons/ep/caret-right')['default']
    IEpCrop: typeof import('~icons/ep/crop')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpList: typeof import('~icons/ep/list')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpMore: typeof import('~icons/ep/more')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpVideoPlay: typeof import('~icons/ep/video-play')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    J: typeof import('../components/rightClickMenu.vue')['default']
    Layout: typeof import('./../components/layout.vue')['default']
    Lyric: typeof import('./../components/Lyric.vue')['default']
    MusicPlay: typeof import('./../components/MusicPlay.vue')['default']
    MusicPlayFooter: typeof import('./../components/MusicPlayFooter.vue')['default']
    RightClickMenu: typeof import('./../components/rightClickMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./../components/Slider.vue')['default']
    SongTable: typeof import('./../components/SongTable.vue')['default']
    TransitionComponent: typeof import('./../components/TransitionComponent.vue')['default']
  }
}
